alert('ok');
prompt('ok?');
console.log('ok');
var no = 7;
const yes = 9;
let maybe = 123;
console.log(no, yes, maybe);
maybe = document.getElementsByTagName('h1');
console.log(maybe);
maybe.innerHtml = 'ok';